[package]
name = "fat32rs"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3

[lib]
name = "fat32rs"
path = "src/lib.rs"

[[example]]
name = "read_files"
path = "examples/read_files.rs"

[dev-dependencies]
tempfile = "3.2.0"
